/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export class ImageImpl {
  static ppmFile2PngFile(ppmPath: string, pngPath: string): boolean
}
